import pygame
import os

class Img:
    def __init__(self):
        # UI, HUD and Backgrounds
        self.riverwood_ui = pygame.image.load(os.path.join('images', 'main_game_bg.png'))
        self.health_bar = pygame.image.load(os.path.join('images', 'health_bar.png'))
        self.exp_bar = pygame.image.load(os.path.join('images', 'xp_bar.png'))
        self.blacksmith_ui = pygame.image.load(os.path.join('images', 'blacksmith_ui.png'))
        self.training_ui = pygame.image.load(os.path.join('images', 'training_ui.png'))
        self.market_ui = pygame.image.load(os.path.join('images', 'market_ui.png'))
        self.tavern_ui = pygame.image.load(os.path.join('images', 'tavern_ui.png'))
        self.main_menu_ui = pygame.image.load(os.path.join('images', 'main_menu_ui.png'))
        self.options_ui = pygame.image.load(os.path.join('images', 'options_ui.png'))
        self.credits_ui = pygame.image.load(os.path.join('images', 'credits_ui.png'))
        self.game_intro_ui = pygame.image.load(os.path.join('images', 'game_intro_ui.png'))
        self.character_ui = pygame.image.load(os.path.join('images', 'character_ui.png'))
        self.my_quests_ui = pygame.image.load(os.path.join("images", "my_quests_ui.png"))
        self.lost_img = pygame.image.load(os.path.join('images', 'lost_img.png'))
        self.bread_icon_float = pygame.image.load(os.path.join("images", '1.png'))
        self.cheese_icon_float = pygame.image.load(os.path.join("images", '2.png'))
        self.apples_icon_float = pygame.image.load(os.path.join("images", '3.png'))
        self.candy_icon_float = pygame.image.load(os.path.join("images", '4.png'))
        self.big_hp_icon_float = pygame.image.load(os.path.join("images", '5.png'))
        self.small_hp_icon_float = pygame.image.load(os.path.join("images", '6.png'))
        self.draught_icon_float = pygame.image.load(os.path.join("images", '7.png'))
        self.phial_icon_float = pygame.image.load(os.path.join("images", '8.png'))
        self.smallpk_icon_float = pygame.image.load(os.path.join("images", '9.png'))
        self.bigpk_icon_float = pygame.image.load(os.path.join("images", '10.png'))
        self.leaf_icon_float = pygame.image.load(os.path.join("images", '11.png'))
        self.syringe_icon_float = pygame.image.load(os.path.join("images", '12.png'))
        self.char_icon_01 = pygame.image.load(os.path.join("images", '13.png'))
        self.char_icon_02 = pygame.image.load(os.path.join("images", '14.png'))
        self.char_icon_03 = pygame.image.load(os.path.join("images", '15.png'))
        self.char_icon_04 = pygame.image.load(os.path.join("images", '16.png'))
        self.char_icon_05 = pygame.image.load(os.path.join("images", '17.png'))
        self.char_icon_06 = pygame.image.load(os.path.join("images", '18.png'))
        self.char_icon_07 = pygame.image.load(os.path.join("images", '19.png'))
        self.char_icon_08 = pygame.image.load(os.path.join("images", '20.png'))
        self.blacksmith_icon_01 = pygame.image.load(os.path.join("images", '21.png'))
        self.blacksmith_icon_02 = pygame.image.load(os.path.join("images", '22.png'))
        self.blacksmith_icon_03 = pygame.image.load(os.path.join("images", '23.png'))
        self.blacksmith_icon_04 = pygame.image.load(os.path.join("images", '24.png'))
        self.battle_screen = pygame.image.load(os.path.join('images', 'battle_screen.png'))
        self.battle_screen2 = pygame.image.load(os.path.join('images', 'battle_screen2.png'))
        self.battle_screen3 = pygame.image.load(os.path.join('images', 'battle_screen3.png'))
        self.battle_light = pygame.image.load(os.path.join('images', 'battle_light.png'))
        self.main_map = pygame.image.load(os.path.join('images', 'map.png'))
        self.square_icon = pygame.image.load(os.path.join('images', 'square_icon.png'))
        # Inventory Icons
        self.apple_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'apple.png')), (50, 50))
        self.bread_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'bread.png')), (50, 50))
        self.candy_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'candy.png')), (50, 50))
        self.cheese_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'cheese.png')), (50, 50))
        self.big_potion_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'health.png')), (50, 50))
        self.small_potion_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'shp.png')), (50, 50))
        self.draught_of_luck_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'dol.png')), (50, 50))
        self.phial_of_protection_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'phial.png')), (50, 50))
        self.small_painkiller_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'pill.png')), (50, 50))
        self.big_painkiller_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'pills.png')), (50, 50))
        self.lucky_leaf_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'lucky_leaf.png')), (50, 50))
        self.syringe_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'syringe.png')), (50, 50))
        # player things
        self.bow = pygame.image.load(os.path.join('images', 'bow.png'))
        self.sword = pygame.image.load(os.path.join('images', 'sword.png'))
        self.weapon_square = pygame.image.load(os.path.join('images', 'weapon_square.png'))

        # Enemy Icon
        self.guard_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'helmet.png')), (50, 50))
        self.hunter_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'hunter.png')), (50, 50))
        self.looters_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'looters.png')), (50, 50))

        # RES + LOAD ICONS
        self.blank_bar = pygame.transform.scale(pygame.image.load(os.path.join('images', 'blank_bar.png')), (135, 33))
        self.attack_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'attack_icon.png')), (28, 28))
        self.defence_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'defence_icon.png')), (28, 28))
        self.strength_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'strength_icon.png')), (28, 28))
        self.player_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'player_icon.png')), (50, 50))
        self.battle_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'battle_icon.png')), (50, 50))
        self.door_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'door.png')), (50, 50))
        self.gold_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'gold_icon.png')), (50, 50))
        self.exp_bonus_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'exp_bonus_icon.png')), (50, 50))
        self.health_icon = pygame.transform.scale(pygame.image.load(os.path.join("images", "health_icon.png")), (50, 50))
        self.random_quest_icon = pygame.transform.scale(pygame.image.load(os.path.join("images", "envelope.png")), (40, 40))
        self.dl1_ui = pygame.image.load(os.path.join('images', 'dl1.png'))
        # Event icons
        self.prisoner_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'prisoner.png')), (50, 50))
        self.events_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'events.png')), (50, 50))
        self.next_level = pygame.transform.scale(pygame.image.load(os.path.join('images', 'next_level.png')), (50, 50))
        self.prisoners_image = pygame.transform.scale(pygame.image.load(os.path.join('images', 'prisoners_image.png')), (550, 280))
        self.prisoners_image2 = pygame.transform.scale(pygame.image.load(os.path.join('images', 'prisoners_image2.png')), (550, 280))
        self.prisoners_image3 = pygame.transform.scale(pygame.image.load(os.path.join('images', 'prisoners_image3.png')), (550, 280))
        self.thief_image = pygame.transform.scale(pygame.image.load(os.path.join('images', 'thief_image.png')), (550, 280))
        self.mercenary_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'mercenary.png')), (550, 280))
        self.kneeling_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'kneeling.png')), (550, 280))
        self.hangman_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'hangman.png')), (550, 280))
        self.letter_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'letter.png')), (550, 280))
        self.experience_icon = pygame.transform.scale(pygame.image.load(os.path.join('images', 'experience.png')), (550, 280))
        self.gold_event = pygame.transform.scale(pygame.image.load(os.path.join('images', 'gold_event.png')), (550, 280))
        self.battle_won = pygame.transform.scale(pygame.image.load(os.path.join('images', 'battle_won.png')), (550, 280))
        self.battle_lost = pygame.transform.scale(pygame.image.load(os.path.join('images', 'battle_lost.png')), (550, 280))
        self.not_available = pygame.transform.scale(pygame.image.load(os.path.join("images", "not_available.png")), (51, 51))
        self.dungeon_exit = pygame.transform.scale(pygame.image.load(os.path.join("images", "dungeon_exit.png")), (550, 280))
        # Quests text
        self.dragon_treasure_intro = pygame.transform.scale(pygame.image.load(os.path.join("images", "dragon_treasure_intro.png")), (550, 280))
        self.dragon_treasure_quest = pygame.transform.scale(pygame.image.load(os.path.join("images", "dragon_treasure_quest.png")), (550, 280))
        self.dragon_treasure_part1 = pygame.transform.scale(pygame.image.load(os.path.join("images", "dragon_treasure_part1.png")), (550, 280))
        self.dragon_treasure_part2 = pygame.transform.scale(pygame.image.load(os.path.join("images", "dragon_treasure_part2.png")), (550, 280))
        self.dragon_treasure_part3 = pygame.transform.scale(pygame.image.load(os.path.join("images", "dragon_treasure_part3.png")), (550, 280))
        self.the_kneeling_one_intro = pygame.transform.scale(pygame.image.load(os.path.join("images", "the_kneeling_one_intro.png")), (550, 280))
        self.the_kneeling_one_part1 = pygame.transform.scale(pygame.image.load(os.path.join("images", "the_kneeling_one_part1.png")), (550, 280))
        self.the_kneeling_one_part2 = pygame.transform.scale(pygame.image.load(os.path.join("images", "the_kneeling_one_part2.png")), (550, 280))
        self.the_kneeling_one_part3 = pygame.transform.scale(pygame.image.load(os.path.join("images", "the_kneeling_one_part3.png")), (550, 280))
        self.the_kneeling_one_part4 = pygame.transform.scale(pygame.image.load(os.path.join("images", "the_kneeling_one_part4.png")), (550, 280))

        self.desperate_woman_intro = pygame.transform.scale(pygame.image.load(os.path.join("images", "desperate_woman_intro.png")), (550, 280))
        self.desperate_woman_part1 = pygame.transform.scale(pygame.image.load(os.path.join("images", "desperate_woman_part1.png")), (550, 280))
        self.desperate_woman_part2 = pygame.transform.scale(pygame.image.load(os.path.join("images", "desperate_woman_part2.png")), (550, 280))
        self.desperate_woman_part3 = pygame.transform.scale(pygame.image.load(os.path.join("images", "desperate_woman_part3.png")), (550, 280))
        self.desperate_woman_part4 = pygame.transform.scale(pygame.image.load(os.path.join("images", "desperate_woman_part4.png")), (550, 280))
        self.criminal_activity_intro = pygame.transform.scale(pygame.image.load(os.path.join("images", "the_kneeling_one_part4.png")), (550, 280))
        self.criminal_activity_part1 = pygame.transform.scale(pygame.image.load(os.path.join("images", "the_kneeling_one_part4.png")), (550, 280))
        self.criminal_activity_part2 = pygame.transform.scale(pygame.image.load(os.path.join("images", "the_kneeling_one_part4.png")), (550, 280))
        self.the_kneeling_one_part4 = pygame.transform.scale(pygame.image.load(os.path.join("images", "the_kneeling_one_part4.png")), (550, 280))
        self.the_kneeling_one_part4 = pygame.transform.scale(pygame.image.load(os.path.join("images", "the_kneeling_one_part4.png")), (550, 280))
        # Quest Icon
        self.quest_icon = pygame.transform.scale(pygame.image.load(os.path.join("images", "quest.png")), (30, 30))
        self.dragon_necklace = pygame.transform.scale(pygame.image.load(os.path.join("images", "dragon_necklace.png")), (50, 50))

img = Img()